[package]
name = "csgo-friendcode"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
bitintr = "0.3.0"
md5 = "0.7.0"